logging:
  structured:
    format:
      console: ecs
    json:
      add:
        sha: "@commit.sha@"
      stacktrace:
        root: first
        max-length: 12288
        include-common-frames: true
        include-hashes: true
