name: PR Help Comment
run-name: PR Help Comment

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  prHelpComment:
    name: PR Help Comment
    runs-on: ubuntu-latest

    steps:
      - name: Help Comment
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/composite/setup-ci
        with:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run script
        shell: bash
        run: bun .github/scripts/help-message
        env:
          PR_ID: ${{ github.event.pull_request.number }}
