name: Verify PR
run-name: Running PR verification on ${{ github.actor }}'s branch

on:
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verifyPr:
    name: Run verification checks on the PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run composite workflow
        uses: ./.github/composite/notion-checks
        id: notion_check
        with:
          PR_ID: ${{ github.event.number }}
