name: Verify PR
run-name: Running PR verification on ${{ github.actor }}'s branch

on:
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verifyPr:
    name: Run verification checks on the PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load secrets
        uses: ./.github/composite/load-secrets
        with:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          UNLOAD_ENVIRONMENTS: ci

      - name: Run 'Check Notion PR' composite action
        uses: ./.github/composite/check-notion-pr
        id: notion_check
        with:
          PR_ID: ${{ github.event.number }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Echo Notion context
        run: |
          echo "Context: ${{ steps.notion_check.outputs.context }}"

      - name: Qodo PR-Agent
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ env.GEMINI_API_KEY }}
          config.verbosity_level: "2"
          pr_reviewer.extra_instructions: "Review this PR in the context of the following Notion task: ${{ steps.notion_check.outputs.context }}"
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"

      - name: Run 'Check Notion Commits' composite action
        uses: ./.github/composite/check-notion-commits
        with:
          PR_ID: ${{ github.event.number }}
          NOTION_ID: ${{ steps.notion_check.outputs.notion_id }}
